# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-02 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20200602_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='profile',
            new_name='user',
        ),
    ]
