# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-02 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20200602_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
