# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-02 17:01
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20200602_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=pyuploadcare.dj.models.ImageField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
