# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-03 03:29
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_auto_20200602_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
