# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-03 05:57
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_auto_20200603_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
